version: '3.8'

services:
  bookworm-api:
    container_name: bw-api
    image: bookworm-api:latest
    ports:
      - 8000:8000
    restart: always
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - CHROMA_AUTH_CREDENTIALS=${CHROMA_AUTH_CREDENTIALS}